import test from 'node:test';
import assert from 'node:assert/strict';
import { videoIdFromInput, parseCaptionBody, captionType, YouTubeExtractor, EXTRACTOR_VERSION, assertUpstream, retryAfterSeconds } from '../lib/youtube-extractor.mjs';
import { SnapshotCache, chunkSegments, encodeCursor, decodeCursor, PAGE_BYTES } from '../lib/snapshot-cache.mjs';
import { TranscriptService, authorize } from '../lib/transcript-service.mjs';
import { handleMcp } from '../lib/mcp-handler.mjs';
import { TranscriptError } from '../lib/transcript-errors.mjs';
import { localDb } from './sqlite-adapter.mjs';
const id='AJpK3YTTKZ4',url=`https://www.youtube.com/watch?v=${id}`;
const code=(expected)=>error=>error.code===expected;
const player=(tracks=[])=>({playabilityStatus:{status:'OK'},videoDetails:{title:'Synthetic test fixture',lengthSeconds:'1000'},captions:{playerCaptionsTracklistRenderer:{captionTracks:tracks}}});
const track={languageCode:'en',vssId:'a.en',kind:'asr',baseUrl:`https://www.youtube.com/api/timedtext?v=${id}&lang=en&signature=DO_NOT_EXPOSE`};
const segments=(n=260)=>Array.from({length:n},(_,i)=>({text:`synthetic cue ${i}\n A &amp; B`,start:i*2,duration:2,duration_source:'upstream'}));
const fixture=(n=260)=>({video_id:id,source_url:url,selected_language:'en',language:'en',track_id:'a.en',caption_type:'auto_generated',extractor_version:EXTRACTOR_VERSION,retrieved_at:'2026-10-01T00:00:00.000Z',extraction_method:'mock/json3',segments:segments(n),languages:[],content_trust:'untrusted_data'});

test('unit: accepted URL variants and exact host/protocol validation',()=>{
  for(const x of [id,url,`https://youtu.be/${id}?si=abc`,`https://www.youtube.com/shorts/${id}`,`https://www.youtube.com/live/${id}`,`https://www.youtube-nocookie.com/embed/${id}`])assert.equal(videoIdFromInput(x),id);
  for(const x of [`https://evilyoutube.com/watch?v=${id}`,`https://youtube.com.evil.example/watch?v=${id}`,`ftp://youtube.com/watch?v=${id}`,`https://user:pass@youtube.com/watch?v=${id}`,`https://youtube.com:443/watch?v=${id}`.replace(':443',':444'),'bad-id'])assert.throws(()=>videoIdFromInput(x),code('invalid_input'));
});
test('unit: upstream destination validation prevents arbitrary fetch and mismatched video',()=>{
  assert.equal(assertUpstream(track.baseUrl,id).pathname,'/api/timedtext');
  for(const x of ['https://evil.example/api/timedtext?v='+id,'http://youtube.com/api/timedtext?v='+id,'https://www.youtube.com/arbitrary','https://www.youtube.com/api/timedtext?v=aaaaaaaaaaa'])assert.throws(()=>assertUpstream(x,id),code('parsing_failure'));
});
test('unit: JSON3 preserves whitespace, literal entities, repeated and overlapping speech',()=>{
  const body=JSON.stringify({events:[{tStartMs:1000,dDurationMs:2000,segs:[{utf8:'  Hello\n&'},{utf8:'amp; welcome  '}]},{tStartMs:1500,dDurationMs:1000,segs:[{utf8:'Hello'}]},{tStartMs:3000,dDurationMs:1000,segs:[{utf8:'Hello'}]}]});
  const s=parseCaptionBody(body).segments;assert.equal(s.length,3);assert.equal(s[0].text,'  Hello\n&amp; welcome  ');assert.equal(s[0].duration,2);assert.equal(s[2].text,'Hello');
});
test('unit: srv3/classic XML and VTT preserve decoded text and line breaks',()=>{
  assert.equal(parseCaptionBody('<timedtext><body><p t="0" d="2669">A &amp; B<br />next</p></body></timedtext>').segments[0].text,'A & B\nnext');
  assert.deepEqual(parseCaptionBody('<transcript><text start="1.5" dur="2.25">Hello &amp; welcome</text></transcript>').segments[0],{text:'Hello & welcome',start:1.5,duration:2.25,duration_source:'upstream'});
  const s=parseCaptionBody('WEBVTT\n\n00:00:01.000 --> 00:00:03.500\nHello <b>world</b>\nnext\n').segments[0];assert.equal(s.duration,2.5);assert.equal(s.text,'Hello world\nnext');
});
test('unit: truncated XML, malformed payload and negative timing fail without partial success',()=>{
  for(const body of ['<transcript><text start="0" dur="1">A</text><text','<timedtext><body><p t="0" d="1000">A</p><p','<transcript><text start="-1" dur="2">A</text></transcript>','{"events":false}','{"events":[{"tStartMs":0,"dDurationMs":-5,"segs":[{"utf8":"A"}]}]}'])assert.throws(()=>parseCaptionBody(body),code('parsing_failure'));
  assert.throws(()=>parseCaptionBody(''),e=>e.code==='parsing_failure'&&e.details.reason==='empty_caption_response');
});
test('unit: caption type stays unknown unless upstream establishes it',()=>{assert.equal(captionType({kind:'asr'}),'auto_generated');assert.equal(captionType({vssId:'.en'}),'unknown');assert.equal(captionType({isAutoGenerated:false}),'manual');});
test('mocked HTTP: successful real-shaped extractor result never exposes signed upstream URL',async()=>{
  const fetchImpl=async(raw)=>new Response(new URL(raw).pathname.includes('player')?JSON.stringify(player([track])):JSON.stringify({events:[{tStartMs:100,dDurationMs:500,segs:[{utf8:'synthetic caption'}]}]}));
  const r=await new YouTubeExtractor({fetchImpl}).transcript(id);assert.equal(r.segments[0].text,'synthetic caption');assert.equal(r.selected_language,'en');assert.equal(r.caption_type,'auto_generated');assert(!JSON.stringify(r).includes('DO_NOT_EXPOSE'));
});
test('mocked HTTP: language absence is explicit and never silently translated',async()=>{
  const e=new YouTubeExtractor({fetchImpl:async()=>new Response(JSON.stringify(player([track])))});
  await assert.rejects(e.transcript(id,'fr'),code('unavailable_language'));
});
test('mocked HTTP: two playable no-track responses confirm absence; metadata remains available',async()=>{
  const e=new YouTubeExtractor({fetchImpl:async(raw)=>new Response(new URL(raw).pathname.includes('player')?JSON.stringify(player()):'var ytInitialPlayerResponse = '+JSON.stringify(player())+';')});
  const p=await e.getTracks(id,{allowAbsent:true});assert.equal(e.publicInfo(p).caption_availability,'confirmed_absent');assert.equal(e.publicInfo(p).title,'Synthetic test fixture');
  await assert.rejects(new YouTubeExtractor({fetchImpl:e.fetchImpl}).transcript(id),code('no_captions'));
});
test('mocked HTTP: access rejection is distinct from caption absence',async()=>{
  await assert.rejects(new YouTubeExtractor({fetchImpl:async()=>new Response('blocked',{status:403})}).transcript(id),code('access_restriction'));
  await assert.rejects(new YouTubeExtractor({fetchImpl:async()=>new Response(JSON.stringify({playabilityStatus:{status:'LOGIN_REQUIRED',reason:'Sign in to confirm you are not a bot'}}))}).transcript(id),code('access_restriction'));
});
test('mocked HTTP: empty listed timedtext and 404 do not establish caption absence or video unavailability',async()=>{
  for(const status of [200,404]) {
    const fetchImpl=async(raw)=>{const p=new URL(raw).pathname;return p.includes('player')?new Response(JSON.stringify(player([track]))):p==='/watch'?new Response('var ytInitialPlayerResponse = '+JSON.stringify(player([track]))+';'):new Response('',{status});};
    await assert.rejects(new YouTubeExtractor({fetchImpl}).transcript(id),code('parsing_failure'));
  }
});
test('mocked HTTP: redirects are never followed',async()=>{
  let count=0;await assert.rejects(new YouTubeExtractor({fetchImpl:async()=>{count++;return new Response(null,{status:302,headers:{location:'https://evil.example'}});}}).transcript(id),code('access_restriction'));assert.equal(count,1);
});
for (const method of ['getTracks','transcript']) {
  for (const denial of ['http','bot','web']) {
    test(`mocked HTTP: ${method} stops after ${denial} access denial`,async()=>{
      let count=0;
      const extractor=new YouTubeExtractor({fetchImpl:async()=>{
        count++;
        if(denial==='web'&&count===1)return new Response('malformed JSON');
        if(count>(denial==='web'?2:1))assert.fail('request after access denial');
        if(denial==='http')return new Response('blocked',{status:403});
        if(denial==='bot')return new Response(JSON.stringify({playabilityStatus:{status:'LOGIN_REQUIRED',reason:'Sign in to confirm you are not a bot'}}));
        return new Response('<title>Consent</title>');
      }});
      await assert.rejects(extractor[method](id),code('access_restriction'));
      assert.equal(count,denial==='web'?2:1);
    });
  }
}
test('mocked HTTP: timedtext denial stops format and source fallbacks',async()=>{
  for(const status of [401,403,451]) {
    let count=0;
    const extractor=new YouTubeExtractor({fetchImpl:async()=>{
      count++;if(count===1)return new Response(JSON.stringify(player([track])));
      assert.equal(count,2,'no request after timedtext denial');
      return new Response('',{status});
    }});
    await assert.rejects(extractor.transcript(id),code('access_restriction'));assert.equal(count,2);
  }
});
test('mocked HTTP: ordinary player parsing failure still recovers via watch page',async()=>{
  for(const method of ['getTracks','transcript']) {
    let count=0;
    const extractor=new YouTubeExtractor({fetchImpl:async()=>{
      count++;
      return new Response(count===1?'invalid JSON':count===2?'var ytInitialPlayerResponse = '+JSON.stringify(player([track]))+';':JSON.stringify({events:[{tStartMs:0,dDurationMs:1000,segs:[{utf8:'recovered'}]}]}));
    }});
    const result=await extractor[method](id);assert.equal(count,method==='getTracks'?2:3);
    assert.equal(method==='getTracks'?result.tracks.length:result.segments[0].text,method==='getTracks'?1:'recovered');
  }
});
test('mocked HTTP: malformed timedtext still recovers via another format',async()=>{
  let count=0;
  const result=await new YouTubeExtractor({fetchImpl:async()=>{
    count++;return new Response(count===1?JSON.stringify(player([track])):count===2?'malformed captions':JSON.stringify({events:[{tStartMs:0,dDurationMs:1000,segs:[{utf8:'recovered'}]}]}));
  }}).transcript(id);
  assert.equal(count,3);assert.equal(result.segments[0].text,'recovered');
});
test('mocked HTTP: 429 respects long Retry-After without another attempt',async()=>{
  let count=0;await assert.rejects(new YouTubeExtractor({fetchImpl:async()=>{count++;return new Response('',{status:429,headers:{'retry-after':'120'}});},sleep:async()=>assert.fail('must not sleep and retry')}).transcript(id),e=>e.code==='rate_limiting'&&e.details.retry_after_seconds===120);assert.equal(count,1);
  assert.equal(retryAfterSeconds('2'),2);
});
test('mocked HTTP: short transient retry is bounded and honors supplied delay',async()=>{
  let count=0;const waits=[];const e=new YouTubeExtractor({fetchImpl:async()=>{count++;return new Response('',{status:429,headers:{'retry-after':'1'}});},sleep:async(ms)=>waits.push(ms)});
  await assert.rejects(e.transcript(id),code('rate_limiting'));assert.equal(count,2);assert.deepEqual(waits,[1000]);
});
test('mocked HTTP: aborted request is timeout; exhausted total budget never starts fetch',async()=>{
  let count=0;const e=new YouTubeExtractor({budgetMs:5,fetchImpl:async(_u,opts)=>{count++;return new Promise((_r,reject)=>opts.signal.addEventListener('abort',()=>reject(new Error('aborted'))));}});
  await assert.rejects(e.transcript(id),code('timeout'));assert.equal(count,1);
  let now=0;const e2=new YouTubeExtractor({now:()=>now,fetchImpl:async()=>assert.fail('must not fetch')});now=40000;await assert.rejects(e2.transcript(id),code('timeout'));
});
test('local SQLite: pagination/cache uses an immutable snapshot without re-fetching',async()=>{
  const db=localDb();let calls=0;const service=new TranscriptService(db,{extractorFactory:()=>({transcript:async()=>{calls++;return fixture();}})});
  const first=await service.call('get_transcript',{url},'owner');assert.equal(first.cache_status,'miss');assert(first.has_more);let all=[...first.segments],page=first;
  while(page.has_more){page=await service.call('get_transcript',{url,next_cursor:page.next_cursor},'owner');assert.equal(page.snapshot_id,first.snapshot_id);assert.equal(page.first_segment_index,all.length);all.push(...page.segments);}
  assert.deepEqual(all,fixture().segments);assert.equal(page.next_cursor,null);assert.equal(calls,1);
  const repeat=await service.call('get_transcript',{url},'owner');assert.equal(repeat.cache_status,'hit');assert.equal(repeat.snapshot_id,first.snapshot_id);assert.equal(calls,1);
  const replay=await service.call('get_timed_transcript',{url,next_cursor:first.next_cursor},'owner');assert.equal(replay.timed_lines[0].timestamp,'00:04:00.000');assert(replay.timed_lines[0].citation_url.includes('&t=240s'));
});
test('local SQLite: durable cursors enforce owner, video/language and shape without automatic expiry',async()=>{
  let now=1000;const db=localDb(),cache=new SnapshotCache(db,{now:()=>now}),row=await cache.write('owner',fixture(),'en'),p=await cache.page('owner',id,'en',null,row);
  assert.equal(decodeCursor(p.next_cursor).snapshot,row.id);
  await assert.rejects(cache.page('other',id,'en',p.next_cursor),code('snapshot_unavailable'));
  await assert.rejects(cache.page('owner','aaaaaaaaaaa','en',p.next_cursor),code('invalid_cursor'));
  await assert.rejects(cache.page('owner',id,'fr',p.next_cursor),code('invalid_cursor'));
  await assert.rejects(cache.page('owner',id,'en',encodeCursor(row.id,999)),code('invalid_cursor'));
  assert.throws(()=>decodeCursor('bad'),code('invalid_cursor'));now+=365*24*60*60*1000;assert.equal((await cache.page('owner',id,'en',p.next_cursor)).snapshot_id,row.id);
});
test('local SQLite: global concurrency lease allows two extractions and rejects a third',async()=>{
  let now=100;const db=localDb(),a=new SnapshotCache(db,{now:()=>now}),b=new SnapshotCache(db,{now:()=>now});const r1=await a.lease(),r2=await b.lease();await assert.rejects(a.lease(),code('service_busy'));await r1();const r3=await a.lease();await r3();await r2();assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM extractor_leases').get().n,0);
});
test('local SQLite: failed extraction is never cached and releases concurrency lease',async()=>{
  const db=localDb(),service=new TranscriptService(db,{extractorFactory:()=>({transcript:async()=>{throw new TranscriptError('rate_limiting','Synthetic 429',{},true);}})});
  await assert.rejects(service.call('get_transcript',{url},'owner'),code('rate_limiting'));assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM transcript_snapshots').get().n,0);assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM extractor_leases').get().n,0);
});
test('local SQLite: chunk/manifest transaction rolls back on failed chunk insertion',async()=>{
  const db=localDb();db.sqlite.exec("CREATE TRIGGER fail_insert BEFORE INSERT ON transcript_chunks BEGIN SELECT RAISE(ABORT, 'synthetic failure'); END;");
  await assert.rejects(new SnapshotCache(db).write('owner',fixture(),'en'),code('storage_unavailable'));assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM transcript_snapshots').get().n,0);
});
test('local SQLite: retains all successful snapshots without count eviction and bounds metadata',async()=>{
  let now=0;const db=localDb(),cache=new SnapshotCache(db,{now:()=>now});for(let i=0;i<300;i++){now++;await cache.write('owner',fixture(1),'en');}
  assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM transcript_snapshots').get().n,300);assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM transcript_chunks').get().n,300);
  await assert.rejects(cache.write('owner',{...fixture(1),title:'x'.repeat(40000)},'en'),code('response_too_large'));
  assert.throws(()=>chunkSegments([{text:'x'.repeat(PAGE_BYTES),start:0,duration:1}]),code('response_too_large'));
});
const ownerHeaders={'Content-Type':'application/json',Accept:'application/json, text/event-stream','oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.test'};
const req=(method,params,headers=ownerHeaders)=>new Request('https://private.example/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});
test('local MCP handler: discovery advertises single-video and batch tools and initialization works',async()=>{
  const env={OWNER_EMAIL:'owner@example.test'};
  const init=await (await handleMcp(req('initialize',{protocolVersion:'2025-06-18'}),env)).json();assert.equal(init.result.protocolVersion,'2025-06-18');
  const list=await (await handleMcp(req('tools/list',{}),env)).json();assert.deepEqual(list.result.tools.map(t=>t.name),['get_transcript','get_timed_transcript','get_video_info','get_available_languages','get_transcripts','get_creator_transcripts','get_playlist','get_playlist_transcripts','get_video_chapters','get_transcript_range']);
});
test('local MCP handler: authorization denies missing/wrong identity before cache or tools',async()=>{
  assert.throws(()=>authorize(new Headers(), 'owner@example.test'),code('unauthorized'));
  const env={OWNER_EMAIL:'owner@example.test',MCP_AUTH_KEY:'fixture'.repeat(8)};
  assert.equal((await handleMcp(req('tools/list',{}, {'Content-Type':'application/json'}),env)).status,401);
  assert.equal((await handleMcp(req('tools/call',{name:'get_transcript',arguments:{url}},{...ownerHeaders,'oai-authenticated-user-email':'other@example.test'}),env)).status,403);
  assert.equal((await handleMcp(req('tools/list',{}, {...ownerHeaders,Origin:'https://evil.example'}),env)).status,403);
});
test('local MCP handler: version negotiation, unsupported version, Accept and GET Origin checks',async()=>{
  const env={OWNER_EMAIL:'owner@example.test'};
  assert.equal((await handleMcp(req('tools/list',{}, {...ownerHeaders,'mcp-protocol-version':'unsupported'}),env)).status,400);
  assert.equal((await handleMcp(req('tools/list',{}, {...ownerHeaders,Accept:'text/html'}),env)).status,406);
  assert.equal((await handleMcp(new Request('https://private.example/mcp',{headers:ownerHeaders}),env)).status,405);
  assert.equal((await handleMcp(new Request('https://private.example/mcp',{headers:{...ownerHeaders,Origin:'https://evil.example'}}),env)).status,403);
});
test('local MCP handler + real SQLite + mocked extractor: structured tool call and pagination',async()=>{
  const db=localDb(),service=new TranscriptService(db,{extractorFactory:()=>({transcript:async()=>fixture()})}),env={OWNER_EMAIL:'owner@example.test',DB:db};
  const options={serviceFactory:()=>service};const response=await (await handleMcp(req('tools/call',{name:'get_transcript',arguments:{url}}),env,options)).json();
  assert.equal(response.result.isError,false);const first=response.result.structuredContent;assert(first.has_more);
  const next=await (await handleMcp(req('tools/call',{name:'get_transcript',arguments:{url,next_cursor:first.next_cursor}}),env,options)).json();assert.equal(next.result.structuredContent.snapshot_id,first.snapshot_id);
  const invalid=await (await handleMcp(req('tools/call',{name:'get_transcript',arguments:{url:'https://evil.example'}}),env,options)).json();assert.equal(invalid.result.isError,true);assert.equal(invalid.result.structuredContent.error.code,'invalid_input');
});
