import {readFileSync} from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {localDb} from './sqlite-adapter.mjs';
import {handleAcquisition} from '../lib/acquisition-handler.mjs';
import {handleMcp} from '../lib/mcp-handler.mjs';
import {featureRegressions,fixture,list,video,owner} from '../scripts/feature-regressions.mjs';
import {playlistId,playlistPage,videoChapters,MetadataExtractor,validateMetadata,metadataInput,seconds} from '../lib/youtube-metadata.mjs';
import {playlistTool} from '../lib/playlist-tools.mjs';
import {MetadataQueue} from '../lib/metadata-queue.mjs';
import {AcquisitionQueue} from '../lib/acquisition-queue.mjs';
import {SnapshotCache} from '../lib/snapshot-cache.mjs';
import {TranscriptService} from '../lib/transcript-service.mjs';
import {TranscriptError} from '../lib/transcript-errors.mjs';
import {transcriptRange} from '../lib/chapter-range-tools.mjs';
const config={MCP_AUTH_KEY:'fixture'.repeat(8),ACQUISITION_MODE:'private_mac'};
test('actual SQLite feature workflows and signed protocol: frozen playlists, chapters, ranges, overflow and MCP',async()=>{const db=localDb();let env={DB:db,...config};try{const result=await featureRegressions({db,setConfig:async c=>{env={...env,...c};},invoke:r=>new URL(r.url).pathname==='/mcp'?handleMcp(r,env):handleAcquisition(r,env)});assert(result.checks.length>=8);}finally{db.sqlite.close();}});
test('playlist inputs restrict public HTTPS context; URL index never changes authority',()=>{for(const value of [list,`https://youtube.com/playlist?list=${list}`,`https://www.youtube.com/watch?v=${video}&list=${list}&index=90`,`https://youtu.be/${video}?list=${list}`])assert.equal(playlistId(value),list);for(const value of ['http://youtube.com/playlist?list='+list,'https://evil.example/playlist?list='+list,'https://user@youtube.com/playlist?list='+list,'https://youtube.com:444/playlist?list='+list,'https://youtube.com/playlist?list='+list+'&list='+list,'short'])assert.throws(()=>playlistId(value),e=>e.code==='invalid_input');});
const initial=contents=>({metadata:{playlistMetadataRenderer:{title:'Fixture playlist'}},contents:{playlistVideoListRenderer:{playlistId:list,contents}}});
test('playlist parser preserves duplicate / deleted / private slots and reported gaps without inventing totals',()=>{const data=initial([{playlistVideoRenderer:{videoId:video,title:{simpleText:'a'},index:{simpleText:'1'}}},{playlistVideoRenderer:{title:{simpleText:'Deleted video'},index:{simpleText:'4'},isPlayable:false}},{playlistVideoRenderer:{videoId:video,title:{simpleText:'a'},index:{simpleText:'5'},isPlayable:false}}]);const result=playlistPage(data,{playlist_id:list});assert.deepEqual(result.entries.map(e=>e.reported_position),[1,4,5]);assert.equal(result.entries[1].video_id,null);assert.equal(result.entries[2].availability,'unavailable');assert.equal(result.reported_total,null);});
test('playlist malformed identity, ordering, ambiguous continuation and arbitrary endpoints fail closed',()=>{for(const data of [{contents:{playlistVideoListRenderer:{playlistId:'PLdifferent_01',contents:[]}}},initial([{playlistVideoRenderer:{videoId:video,index:{simpleText:'NaN'}}}]),initial([{unknownRenderer:{}}]),initial([{continuationItemRenderer:{continuationEndpoint:{commandMetadata:{webCommandMetadata:{apiUrl:'/evil'}},continuationCommand:{token:'x'}}}}])])assert.throws(()=>playlistPage(data,{playlist_id:list}),e=>e.code==='parsing_failure');assert.throws(()=>metadataInput('playlist_page',{playlist_id:list,continuation:'x',context:{clientVersion:'2.1',url:'https://evil'}}),e=>e.code==='invalid_input');assert.throws(()=>metadataInput('arbitrary_url',{url:'https://evil'}),e=>e.code==='invalid_input');});
const player=description=>({playabilityStatus:{status:'OK'},videoDetails:{videoId:video,title:'Fixture video',lengthSeconds:'90',shortDescription:description}});
const native=starts=>({playerOverlays:{multiMarkersPlayerBarRenderer:{markersMap:[{key:'DESCRIPTION_CHAPTERS',value:{chapters:starts.map((s,i)=>({chapterRenderer:{title:{simpleText:`Native ${i}`},timeRangeStartMillis:s*1000}}))}}]}}});
test('chapters validated native takes precedence over description; exact provenance and bounds',()=>{const r=videoChapters(native([0,30,60]),player('0:00 Description\n0:20 Middle\n1:00 End'),video);assert.equal(r.source,'youtube_native_creator');assert.equal(r.chapters[0].title,'Native 0');assert.equal(r.chapters[2].end,90);assert.equal(r.is_generated,false);});
test('description timestamps independently parsed only if validated, monotonic and beginning at zero',()=>{const r=videoChapters({},player('Intro text\n0:00 Beginning\n0:30 Middle\n1:00 End'),video);assert.equal(r.source,'creator_description');for(const description of ['0:00 A\n0:00 B\n1:00 C','0:02 A\n0:30 B\n1:00 C','0:00 A\n0:30 B\n9:00 C','0:00 A\n0:30 B'])assert.equal(videoChapters({},player(description),video).source,'none');});
test('malformed native safely falls back to validated description or honest empty',()=>{assert.equal(videoChapters(native([0,30,20]),player('0:00 A\n0:30 B\n1:00 C'),video).source,'creator_description');assert.deepEqual(videoChapters(native([5,30]),player('No chapters'),video).chapters,[]);assert.throws(()=>videoChapters({},player(''), 'other000001'),e=>e.code==='parsing_failure');assert.throws(()=>validateMetadata('video_chapters',{video_id:video,title:'x',duration_seconds:30,source:'none',chapters:[{title:'x',start:0}]},{video_id:video}),e=>e.code==='invalid_input');});
test('signed metadata extractor restricts request URLs, explicit denials terminal and malformed JSON controlled',async()=>{let count=0;const denied=new MetadataExtractor({fetchImpl:async()=>{count++;return new Response('denied',{status:403});}});await assert.rejects(denied.acquire('video_chapters',{video_id:video}),e=>e.code==='access_restriction');assert.equal(count,1);await assert.rejects(denied.request('https://evil.example/watch'),e=>e.code==='parsing_failure');const malformed=new MetadataExtractor({fetchImpl:async()=>new Response('{broken')});await assert.rejects(malformed.acquire('playlist_page',{playlist_id:list,continuation:'x',context:{clientVersion:'2.1'}}),e=>e.code==='parsing_failure');});
test('signed metadata extractor parses bounded initial HTML and continuation with fixed browse route',async()=>{const requests=[];const extractor=new MetadataExtractor({fetchImpl:async(url,options)=>{requests.push([url,options]);return new Response(requests.length===1?`var ytInitialData = ${JSON.stringify(initial([{playlistVideoRenderer:{videoId:video,title:{simpleText:'A'},index:{simpleText:'1'}}},{continuationItemRenderer:{continuationEndpoint:{continuationCommand:{token:'next'}}}}]))};ytcfg.set(${JSON.stringify({INNERTUBE_CONTEXT:{client:{clientVersion:'2.1'}}})});`:JSON.stringify({onResponseReceivedActions:[{appendContinuationItemsAction:{continuationItems:[{playlistVideoRenderer:{videoId:video,title:{simpleText:'B'},index:{simpleText:'2'}}}]}}]}));}});const first=await extractor.acquire('playlist_page',{playlist_id:list});assert.equal(first.continuation,'next');const second=await extractor.acquire('playlist_page',{playlist_id:list,continuation:first.continuation,context:first.context});assert.equal(second.entries[0].reported_position,2);assert.equal(requests[1][0],'https://www.youtube.com/youtubei/v1/browse?prettyPrint=false');assert.equal(JSON.parse(requests[1][1].body).context.client.clientName,'WEB');});
test('pending playlist captions get bounded retry cursor without filling later positions; replay frozen',async()=>{const db=localDb();try{const cache=new SnapshotCache(db),service=new TranscriptService(db,{extractorFactory:()=>assert.fail('No cold fetch')});let pending=true,calls=0;const actual=service.call.bind(service);service.call=async(...args)=>{calls++;if(pending)throw new TranscriptError('acquisition_pending','Pending',{},true);return actual(...args);};await cache.write(owner,fixture(video));const metadata={request:async()=>({title:'Pending fixture',entries:[{video_id:video,title:'First',reported_position:1,availability:'reported_public'},{video_id:'feature0002',title:'Later',reported_position:2,availability:'reported_public'}],continuation:null,metadata_id:'m',acquisition_worker_id:'w'})};const options={metadata};const first=await playlistTool('get_playlist_transcripts',service,db,{playlist:list,limit:1},owner,options);assert.equal(first.positions.length,1);assert.equal(first.positions[0].caption_status,'acquisition_pending');assert(first.playlist_cursor);pending=false;const second=await playlistTool('get_playlist_transcripts',service,db,{playlist:list,limit:1,playlist_cursor:first.playlist_cursor},owner,options);assert.equal(second.positions[0].observed_ordinal,1);assert.equal(second.observed_positions_total,1);assert.equal(second.positions[0].caption_status,'success');assert.equal(second.has_more_playlist,false);assert.equal(calls,2);assert.equal((await playlistTool('get_playlist_transcripts',service,db,{playlist:list,limit:1},owner,options)).positions[0].caption_status,'acquisition_pending');}finally{db.sqlite.close();}});
test('metadata and caption jobs share global concurrency two, worker fencing and terminal denial prevents alternate fetch',async()=>{const db=localDb();try{const metadata=new MetadataQueue(db),captions=new AcquisitionQueue(db);await metadata.enqueue(owner,'video_chapters',{video_id:video});await metadata.enqueue(owner,'playlist_page',{playlist_id:list});await captions.enqueue(owner,'feature0002');const a=await metadata.claim('worker',['video_chapters']),b=await captions.claim('worker');assert(a&&b);assert.equal(await metadata.claim('worker',['playlist_page']),null);await assert.rejects(metadata.submit('wrong-worker',{job_id:a.job_id,job_type:a.job_type,token:a.token,failure_code:'access_restriction'}),e=>e.code==='forbidden');const denial={job_id:a.job_id,job_type:a.job_type,token:a.token,failure_code:'access_restriction'};assert.equal((await metadata.submit('worker',denial)).status,'failed');assert.equal((await metadata.submit('worker',denial)).replayed,true);await assert.rejects(captions.enqueue(owner,video),e=>e.code==='access_restriction');const c=await metadata.claim('worker',['playlist_page']);assert(c);await metadata.submit('worker',{job_id:c.job_id,job_type:c.job_type,token:c.token,metadata:{playlist_id:list,title:'x',entries:[],continuation:null}});await assert.rejects(metadata.request(owner,'video_chapters',{video_id:video},{budgetMs:0}),e=>e.code==='access_restriction');}finally{db.sqlite.close();}});
test('range cached ASR boundary cleanup and half-open selection excludes touching cues without caption writes',async()=>{const db=localDb();try{const service=new TranscriptService(db,{extractorFactory:()=>assert.fail('No caption refetch')}),data={...fixture(video,[{text:'we begin here',start:0,duration:2},{text:'we begin here now',start:1,duration:2},{text:'finish',start:3,duration:2}]),caption_type:'auto_generated'};const saved=await service.cache.write(owner,data);const r=await transcriptRange(service,db,{url:video,start:0,end:3},owner);assert.equal(r.selected_segment_count,2);assert(!r.markdown.includes('finish'));assert.equal((r.markdown.match(/we begin/g)||[]).length,1);assert.equal((await service.cache.latest(owner,video)).metadata_json,saved.metadata_json);}finally{db.sqlite.close();}});
test('time syntax strict finite seconds including hours and fractional timestamps',()=>{assert.equal(seconds('01:02:03.5'),3723.5);assert.equal(seconds('00:03.5'),3.5);for(const value of [Infinity,-1,null,'3','1:2','1:60','0:00 trailing'])assert.throws(()=>seconds(value),e=>e.code==='invalid_input');});
test('BU3llOqYy8k evidence fixture: explicit AUTO_CHAPTERS retains all twelve labels/times and automatic provenance',()=>{
 const labels=['Introduction to Codex','Getting started with setup','Configuration and permissions','Data processing demo','Memory and agent context','File and folder management','Plugins and email automation','Leveraging skills for tasks','Generating visual content','Computer use and automation','Automations and scheduling','Coding and website building'];const starts=[0,61,152,308,466,630,746,895,1031,1093,1218,1278];
 const data=native(starts);data.playerOverlays.multiMarkersPlayerBarRenderer.markersMap[0].key='AUTO_CHAPTERS';data.playerOverlays.multiMarkersPlayerBarRenderer.markersMap[0].value.chapters.forEach((c,i)=>c.chapterRenderer.title={simpleText:labels[i]});const p=player('');p.videoDetails.videoId='BU3llOqYy8k';p.videoDetails.lengthSeconds='1500';const r=videoChapters(data,p,'BU3llOqYy8k');assert.equal(r.source,'youtube_auto_chapters');assert.equal(r.is_generated,true);assert.equal(r.creator_provided,false);assert.equal(r.authorship,'automatic');assert.deepEqual(r.chapters.map(c=>c.start),starts);assert.deepEqual(r.chapters.map(c=>c.title),labels);
});
test('macro native chapters unknown authorship is null; explicit auto-generated chapter-panel text establishes automatic source',()=>{
 const contents=[0,30,60].map((s,i)=>({macroMarkersListItemRenderer:{title:{simpleText:`Chapter ${i}`},onTap:{watchEndpoint:{startTimeSeconds:s}}}}));const data={engagementPanelSectionListRenderer:{header:{subtitle:{simpleText:'Chapters'}},content:{macroMarkersListRenderer:{contents}}}};
 const unknown=videoChapters(data,player(''),video);assert.equal(unknown.source,'youtube_native');assert.equal(unknown.is_generated,null);assert.equal(unknown.creator_provided,null);assert.equal(unknown.authorship,'unknown');data.engagementPanelSectionListRenderer.header.subtitle.simpleText='These chapters are auto-generated.';const automatic=videoChapters(data,player(''),video);assert.equal(automatic.source,'youtube_auto_chapters');assert.equal(automatic.is_generated,true);assert.equal(automatic.creator_provided,false);
});
test('metadata transient recovery capped three with cooldown, signature freshness fence and owner isolation',async()=>{const db=localDb();let now=Date.now();db.setClock(()=>now);try{const q=new MetadataQueue(db,{now:()=>now}),id=await q.enqueue(owner,'video_chapters',{video_id:video});for(let i=0;i<3;i++){const job=await q.claim('worker',['video_chapters']);assert(job);const res=await q.submit('worker',{job_id:job.job_id,job_type:job.job_type,token:job.token,failure_code:'network_failure'});assert.equal(res.status,i<2?'queued':'failed');now+=30001;}
 const third=db.sqlite.prepare('SELECT * FROM metadata_jobs WHERE id=?').get(id);assert.equal(third.attempts,3);assert.equal(await q.enqueue(owner,'video_chapters',{video_id:video}),id);assert.equal(db.sqlite.prepare('SELECT status FROM metadata_jobs WHERE id=?').get(id).status,'failed');now+=900001;await q.enqueue(owner,'video_chapters',{video_id:video});assert.equal(db.sqlite.prepare('SELECT attempts FROM metadata_jobs WHERE id=?').get(id).attempts,0);
 assert.notEqual(id,await q.enqueue('other','video_chapters',{video_id:video}));const job=await q.claim('worker',['video_chapters']);await assert.rejects(q.submit('worker',{job_id:job.job_id,job_type:job.job_type,token:job.token,metadata:{video_id:video,title:'x',duration_seconds:10,chapters:[],source:'none'}},{authValidUntil:now-1}),e=>e.code==='claim_expired');assert.equal(db.sqlite.prepare('SELECT status FROM metadata_jobs WHERE id=?').get(job.job_id).status,'leased');
 }finally{db.sqlite.close();}});
test('worker new typed metadata survives lost upload/restart and terminal metadata denial fences caption fetching',async()=>{
 const {PrivateWorker,signedRequest}=await import('../scripts/private-acquisition-worker.mjs');const {generateKeyPairSync}=await import('node:crypto');const {mkdtemp,rm}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const path=await import('node:path');const root=await mkdtemp(path.join(tmpdir(),'synthetic-metadata-worker-')),db=localDb(),keys=generateKeyPairSync('ed25519');let now=Date.now(),retrievals=0,lost=true;db.setClock(()=>now);const env={DB:db,ACQUISITION_PUBLIC_KEY:keys.publicKey.export({type:'spki',format:'der'}).subarray(-32).toString('hex')},q=new MetadataQueue(db,{now:()=>now});const options={root,privateKey:keys.privateKey,now:()=>now,base:'https://synthetic.example',sleep:async()=>{},fetchImpl:async r=>{if(new URL(r.url).pathname.endsWith('/submit')&&lost)return new Response('',{status:500});return handleAcquisition(r,env,{now:()=>now});},metadataExtractorFactory:()=>({acquire:async()=>{retrievals++;return {video_id:video,title:'Typed cached metadata',duration_seconds:30,source:'none',chapters:[]};}}),extractorFactory:()=>assert.fail('Metadata denial must prevent any caption request')};
 try{await q.enqueue(owner,'video_chapters',{video_id:video});await assert.rejects(new PrivateWorker(options).once(),/worker_http_500/);assert.equal(retrievals,1);now+=120001;lost=false;const receipt=await new PrivateWorker(options).once();assert.equal(receipt.status,'complete');assert.equal(receipt.local_cache,'hit');assert.equal(retrievals,1);assert.equal((await q.request(owner,'video_chapters',{video_id:video},{budgetMs:0})).title,'Typed cached metadata');
 const denied=new PrivateWorker({...options,metadataExtractorFactory:()=>({acquire:async()=>{retrievals++;throw new TranscriptError('access_restriction','Explicit synthetic upstream denial');}})}),job={job_id:'a'.repeat(64),owner_namespace:'b'.repeat(64),job_type:'video_chapters',input:{video_id:'denied00001'}};await assert.rejects(denied.localMetadata(job),e=>e.code==='access_restriction');const restarted=new PrivateWorker(options);await assert.rejects(restarted.localResult({job_id:'c'.repeat(64),owner_namespace:job.owner_namespace,video_id:job.input.video_id}),e=>e.code==='access_restriction');assert.equal(retrievals,2);
 }finally{await rm(root,{recursive:true,force:true});db.sqlite.close();}
});
test('playlist overflow is explicit, whole envelope bounded and duplicate positions point to one caption result',async()=>{const db=localDb();try{const service=new TranscriptService(db,{extractorFactory:()=>assert.fail('No refetch')}),segments=Array.from({length:900},(_,i)=>({text:`${i} `+'中\\"'.repeat(180),start:i,duration:1}));await service.cache.write(owner,fixture(video,segments));const metadata={request:async()=>({title:'Bounded playlist fixture',entries:[1,2].map(i=>({video_id:video,title:'Same oversized video',reported_position:i,availability:'reported_public'})),continuation:null,metadata_id:'m',acquisition_worker_id:'w'})};const r=await playlistTool('get_playlist_transcripts',service,db,{playlist:list},owner,{metadata});const {responseBytes}=await import('../lib/transcript-batch.mjs');assert(responseBytes(r)<=245760);assert.equal(r.results.length,1);assert.equal(r.results[0].delivery,'paged');assert(r.next_cursors[video]);assert.equal(r.positions[0].caption_reference,r.positions[1].caption_reference);assert(r.markdown.includes('More captions remain'));}finally{db.sqlite.close();}});
test('additive production migration creates only metadata/workflows while retaining stored caption snapshot/defaults',async()=>{const {DatabaseSync}=await import('node:sqlite');const {readFileSync}=await import('node:fs');const sqlite=new DatabaseSync(':memory:');try{for(const migration of ['0000_typical_blink','0001_faithful_dracula','0002_cooing_tigra','0003_spotty_red_hulk','0004_demonic_dragon_lord']){sqlite.exec(readFileSync(new URL(`../drizzle/${migration}.sql`,import.meta.url),'utf8'));}const tables=sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(r=>r.name);assert(tables.includes('transcript_snapshots'));sqlite.prepare('INSERT INTO transcript_snapshots(id,owner_key,video_id,request_lang,resolved_lang,track_id,extractor_version,cache_key,retrieved_ms,expires_at,bytes,page_count,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run('old-success',owner,video,'__default__','en','.en','legacy','key',1,Number.MAX_SAFE_INTEGER,1,1,'{"segment_hash":"old-immutable-hash"}');const sql=readFileSync(new URL('../drizzle/0005_nappy_starbolt.sql',import.meta.url),'utf8');assert(!/\b(?:UPDATE|DELETE|DROP|ALTER)\b/i.test(sql.replace(/ON UPDATE no action ON DELETE cascade/ig,'')));sqlite.exec(sql);assert.equal(sqlite.prepare('SELECT metadata_json FROM transcript_snapshots WHERE id=?').get('old-success').metadata_json,'{"segment_hash":"old-immutable-hash"}');assert(sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='metadata_jobs'").get());}finally{sqlite.close();}});
test('playlist limits and scan bound are honest, at most ten positions per call and no invented total',async()=>{const db=localDb();try{const service=new TranscriptService(db),metadata={request:async(_owner,_kind,input)=>({title:'Bounded scan',entries:[{video_id:video,title:'Reported item',reported_position:null,availability:'reported_public'}],continuation:`next-${input.continuation??'start'}`,context:{clientVersion:'2.1'},metadata_id:'m',acquisition_worker_id:'w'})};for(const limit of [0,101,1.5])await assert.rejects(playlistTool('get_playlist',service,db,{playlist:list,limit},owner,{metadata}),e=>e.code==='invalid_input');let args={playlist:list,limit:100},result,calls=0;do{result=await playlistTool('get_playlist',service,db,args,owner,{metadata});assert(result.positions.length<=10);calls++;args={...args,playlist_cursor:result.playlist_cursor};}while(result.has_more_playlist);assert.equal(calls,20);assert.equal(result.partial_reason,'playlist_scan_bound');assert.equal(result.observed_positions_total,20);assert.equal(result.selection_complete,false);assert.equal(result.playlist.reported_total,null);}finally{db.sqlite.close();}});
test('stale chapter manifest rejected without editing or refetching caption snapshots',async()=>{const {videoChapterTool}=await import('../lib/chapter-range-tools.mjs');const db=localDb();try{const service=new TranscriptService(db,{extractorFactory:()=>assert.fail('No refetch')}),saved=await service.cache.write(owner,fixture(video));const metadata={request:async()=>validateMetadata('video_chapters',{video_id:video,title:'x',duration_seconds:10,source:'youtube_native',chapters:[{start:0,title:'Native unknown'}]},{video_id:video})};const old=await videoChapterTool(service,db,{url:video},owner,{metadata,now:()=>1000});await db.prepare('INSERT INTO chapter_manifests(id,owner_key,video_id,created_ms,document_json) VALUES(?,?,?,?,?)').bind('f'.repeat(64),owner,video,2000,JSON.stringify({source:'youtube_native'})).run();await assert.rejects(transcriptRange(service,db,{url:video,chapter_id:old.chapters[0].id},owner),e=>e.code==='invalid_input');assert.equal((await service.cache.latest(owner,video)).metadata_json,saved.metadata_json);}finally{db.sqlite.close();}});
test('playlist valid-shaped constructor ID cannot collide with inherited dedup dictionary properties',async()=>{const db=localDb();try{const service=new TranscriptService(db,{extractorFactory:()=>assert.fail('No refetch')});await service.cache.write(owner,fixture('constructor'));const metadata={request:async()=>({title:'Dictionary fixture',entries:[{video_id:'constructor',title:'Real-shaped ID',reported_position:1,availability:'reported_public'}],continuation:null,metadata_id:'m',acquisition_worker_id:'w'})};const r=await playlistTool('get_playlist_transcripts',service,db,{playlist:list},owner,{metadata});assert.equal(r.results.length,1);assert.equal(r.positions[0].caption_status,'success');}finally{db.sqlite.close();}});

test('native empty/null timing never invents zero chapter starts',()=>{for(const value of ['',null]){const data=native([0,30]);data.playerOverlays.multiMarkersPlayerBarRenderer.markersMap[0].value.chapters[0].chapterRenderer.timeRangeStartMillis=value;assert.deepEqual(videoChapters(data,player(''),video).chapters,[]);}});

test('range zero-duration point cues include exact start, exclude end and keep immutable zero bounds',async()=>{
 const db=localDb();try{const service=new TranscriptService(db,{extractorFactory:()=>assert.fail('No refetch')}),data=fixture(video,[{text:'before point',start:1,duration:0},{text:'exact start point',start:2,duration:0},{text:'inside point',start:2.5,duration:0},{text:'exact end point',start:3,duration:0},{text:'timed overlap',start:1.5,duration:1}]),saved=await service.cache.write(owner,data);
 const range=await transcriptRange(service,db,{url:video,start:2,end:3},owner);assert.equal(range.selected_segment_count,3);assert(range.markdown.includes('exact start point'));assert(range.markdown.includes('inside point'));assert(!range.markdown.includes('before point'));assert(!range.markdown.includes('exact end point'));assert.deepEqual(range.actual_selected_coverage,{start:1.5,end:2.5});assert.equal((await service.cache.latest(owner,video)).metadata_json,saved.metadata_json);
 const point=await transcriptRange(service,db,{url:video,start:2.5,end:2.6},owner);assert.equal(point.selected_segment_count,1);assert.deepEqual(point.actual_selected_coverage,{start:2.5,end:2.5});assert(point.boundary_warning.includes('zero-duration point cues'));
 }finally{db.sqlite.close();}
});

const liveList='PLVbBUaEh8wTzYVwTnUZ3e7IeS8jpYEInE';
const liveFixture=()=>JSON.parse(readFileSync(new URL('./fixtures/live-playlist-lockups.json',import.meta.url)));
const liveRows=d=>d.contents.twoColumnBrowseResultsRenderer.tabs[0].tabRenderer.content.sectionListRenderer.contents[0].itemSectionRenderer.contents;
test('exact sanitized live item-section lockups preserve eleven ordered positions and title, ignoring menu IDs',()=>{const r=playlistPage(liveFixture(),{playlist_id:liveList});assert.equal(r.title,'AI Agents');assert.deepEqual(r.entries.map(x=>x.video_id),['BU3llOqYy8k','-fxtfrl7WTk','ZkYxLIsqJoo','xRmzLHnssXE','ELBIb8z0jxc','ASjITM7lVC8','CwvzZgKG_JI','Kg3VhofbCDg','jCo4iV3HXfg','iadTw0HwfNA','MgApOtgso5c']);assert.deepEqual(r.entries.map(x=>x.reported_position),Array.from({length:11},(_,i)=>i+1));assert.equal(r.reported_total,null);});
test('modern identity, type and reported zero-based index fail closed',()=>{for(const mutate of [r=>r.contentId='other000001',r=>r.contentType='LOCKUP_CONTENT_TYPE_PLAYLIST',r=>r.rendererContext.commandContext.onTap.innertubeCommand.watchEndpoint.playlistId='PLwrongplaylist',r=>r.rendererContext.commandContext.onTap.innertubeCommand.watchEndpoint.index=-1,r=>r.rendererContext.commandContext.onTap.innertubeCommand.watchEndpoint.index=1.5]){const d=liveFixture();mutate(liveRows(d)[0].lockupViewModel);assert.throws(()=>playlistPage(d,{playlist_id:liveList}),e=>e.code==='parsing_failure');}});
test('richGrid mixed modern/legacy retains duplicates unavailable holes unknown positions and continuation order',()=>{const d=liveFixture(),rows=liveRows(d),a=structuredClone(rows[0]);delete a.lockupViewModel.rendererContext.commandContext.onTap.innertubeCommand.watchEndpoint.index;const root=[rows[0],{playlistVideoRenderer:{title:{simpleText:'Deleted video'},isPlayable:false,index:{simpleText:'4'}}},{richItemRenderer:{content:a}},{continuationItemRenderer:{continuationEndpoint:{commandMetadata:{webCommandMetadata:{apiUrl:'/youtubei/v1/browse'}},continuationCommand:{token:'bounded-token'}}}}];d.contents.twoColumnBrowseResultsRenderer.tabs[0].tabRenderer.content={richGridRenderer:{contents:root}};const r=playlistPage(d,{playlist_id:liveList});assert.deepEqual(r.entries.map(e=>e.reported_position),[1,4,null]);assert.equal(r.entries[1].availability,'unavailable');assert.equal(r.entries[0].video_id,r.entries[2].video_id);assert.equal(r.continuation,'bounded-token');const next=playlistPage({onResponseReceivedActions:[{appendContinuationItemsAction:{continuationItems:[rows[1],rows[2]]}}]},{playlist_id:liveList},{initial:false});assert.deepEqual(next.entries.map(e=>e.reported_position),[2,3]);});
test('selected playlist tab excludes unselected recommendations; modern extractor uses captured body without network',async()=>{const d=liveFixture();d.contents.twoColumnBrowseResultsRenderer.tabs.push({tabRenderer:{selected:false,content:{richGridRenderer:{contents:[{lockupViewModel:{contentId:'wrong'}}]}}}});const calls=[];const extractor=new MetadataExtractor({fetchImpl:async(url)=>{calls.push(url);return new Response('var ytInitialData = '+JSON.stringify(d)+'; ytcfg.set('+JSON.stringify({INNERTUBE_CONTEXT:{client:{clientVersion:'2.20261002'}}})+');');}});const result=await extractor.acquire('playlist_page',{playlist_id:liveList});assert.equal(result.entries.length,11);assert.equal(calls.length,1);});

const fullLiveFixture=()=>JSON.parse(readFileSync(new URL('./fixtures/live-playlist-full-continuation.json',import.meta.url)));
const fullSections=d=>d.contents.twoColumnBrowseResultsRenderer.tabs[0].tabRenderer.content.sectionListRenderer.contents;
test('full captured modern continuation survives complete MetadataExtractor HTML/config and browse acquisition',async()=>{const d=fullLiveFixture(),vm=fullSections(d)[1].continuationItemViewModel;const opaque='synthetic-opaque-token+/=not-a-credential';vm.continuationCommand.innertubeCommand.continuationCommand.token=opaque;const calls=[];const next={onResponseReceivedActions:[{appendContinuationItemsAction:{continuationItems:[liveRows(d)[0],{continuationItemViewModel:structuredClone(vm)}]}}]};const extractor=new MetadataExtractor({fetchImpl:async(url,options)=>{calls.push({url,options});return new Response(options?.method==='POST'?JSON.stringify(next):'var ytInitialData = '+JSON.stringify(d)+'; ytcfg.set('+JSON.stringify({INNERTUBE_CONTEXT:{client:{clientVersion:'2.20261002',visitorData:'synthetic-visitor'}}})+');');}});const r=await extractor.acquire('playlist_page',{playlist_id:liveList});assert.equal(r.entries.length,11);assert.deepEqual(r.entries.map(e=>e.reported_position),Array.from({length:11},(_,i)=>i+1));assert.equal(r.continuation,opaque);assert.equal(r.context.clientVersion,'2.20261002');assert(new TextEncoder().encode(JSON.stringify(r)).length<256*1024);const continuation=await extractor.acquire('playlist_page',{playlist_id:liveList,continuation:r.continuation,context:r.context});assert.equal(continuation.entries.length,1);assert.equal(continuation.continuation,opaque);assert.equal(JSON.parse(calls[1].options.body).continuation,opaque);assert.equal(calls[1].url,'https://www.youtube.com/youtubei/v1/browse?prettyPrint=false');});
test('modern continuation strict command route request enum trigger unknown commands and duplicates fail closed',()=>{for(const mutate of [v=>v.trigger='OTHER',v=>v.continuationCommand.innertubeCommand.commandMetadata.webCommandMetadata.apiUrl='/evil',v=>v.continuationCommand.innertubeCommand.commandMetadata.webCommandMetadata.sendPost=false,v=>v.continuationCommand.innertubeCommand.continuationCommand.request='OTHER',v=>v.continuationCommand.innertubeCommand.watchEndpoint={videoId:video},v=>v.continuationCommand.innertubeCommand.continuationCommand.token='']){const d=fullLiveFixture();mutate(fullSections(d)[1].continuationItemViewModel);assert.throws(()=>playlistPage(d,{playlist_id:liveList}),e=>e.code==='parsing_failure');}const d=fullLiveFixture();fullSections(d).push(structuredClone(fullSections(d)[1]));assert.throws(()=>playlistPage(d,{playlist_id:liveList}),e=>e.code==='parsing_failure');fullSections(d).pop();fullSections(d).push({unknownViewModel:{}});assert.throws(()=>playlistPage(d,{playlist_id:liveList}),e=>e.code==='parsing_failure');});
test('captured continuation SQLite limit11 ten-cap replay and pending next-page recovery preserve frozen positions',async()=>{const db=localDb();try{const service=new TranscriptService(db,{extractorFactory:()=>assert.fail('No captions fetched')}),feed=playlistPage(fullLiveFixture(),{playlist_id:liveList});feed.context={clientVersion:'2.20261002'};let pending=true,calls=0;const metadata={request:async(_owner,_kind,input)=>{calls++;if(!input.continuation)return {...feed,metadata_id:'initial',acquisition_worker_id:'synthetic'};if(pending)throw new TranscriptError('acquisition_pending','Pending',{},true);return {...playlistPage({onResponseReceivedActions:[{appendContinuationItemsAction:{continuationItems:[{playlistVideoRenderer:{title:{simpleText:'Deleted'},index:{simpleText:'15'},isPlayable:false}}]}}]},{playlist_id:liveList},{initial:false}),metadata_id:'next',acquisition_worker_id:'synthetic'};}};const args={playlist:liveList,limit:11},first=await playlistTool('get_playlist',service,db,args,owner,{metadata});assert.equal(first.positions.length,10);const second=await playlistTool('get_playlist',service,db,{...args,playlist_cursor:first.playlist_cursor},owner,{metadata});assert.equal(second.positions.length,1);assert.equal(second.positions[0].position,11);assert.equal(second.has_more_playlist,false);assert.equal(calls,1);assert.equal((await playlistTool('get_playlist',service,db,{...args,playlist_cursor:first.playlist_cursor},owner,{metadata})).replayed,true);const wide={playlist:liveList,limit:12};const a=await playlistTool('get_playlist',service,db,wide,owner,{metadata}),b=await playlistTool('get_playlist',service,db,{...wide,playlist_cursor:a.playlist_cursor},owner,{metadata});await assert.rejects(playlistTool('get_playlist',service,db,{...wide,playlist_cursor:b.playlist_cursor},owner,{metadata}),e=>e.code==='acquisition_pending');pending=false;const c=await playlistTool('get_playlist',service,db,{...wide,playlist_cursor:b.playlist_cursor},owner,{metadata});assert.equal(c.positions[0].position,15);assert.equal(c.positions[0].availability,'unavailable');assert.equal(c.has_more_playlist,false);assert.equal((await playlistTool('get_playlist',service,db,{...wide,playlist_cursor:b.playlist_cursor},owner,{metadata})).replayed,true);}finally{db.sqlite.close();}});
