// Shared default-track policy for upstream selection, Sites and Mac caches.
export const DEFAULT_POLICY='upstream-default-v1';
export const DEFAULT_JOB_LANGUAGE='__default_upstream_v1__';
const bases=new Set(['default_audio_caption_index','default_caption_index','default_audio_language','single_language']);
const language=value=>typeof value==='string'?value.toLowerCase():null;
const sameLanguage=(a,b)=>language(a)===language(b)||language(a)?.split('-')[0]===language(b)?.split('-')[0];
const preferred=items=>items.find(x=>x.track.kind==='manual'||x.track.isAutoGenerated===false)??items[0];
const indexed=(value,items)=>Number.isInteger(value)&&value>=0&&value<items.length?items[value]:null;
export function resolveDefaultTrack(tracks,renderer={}) {
  const items=tracks.map((track,index)=>({track,index}));if(!items.length)return null;
  const finish=(chosen,basis)=>chosen?{...chosen,basis}:null;
  let audio=null,audioLanguage=null;
  if(renderer.defaultAudioTrackIndex!==undefined){
    audio=indexed(renderer.defaultAudioTrackIndex,renderer.audioTracks??[]);if(!audio)return null;
    const match=typeof audio.audioTrackId==='string'?audio.audioTrackId.match(/^([A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8}){0,3})(?:\.\d+)?$/):null;
    audioLanguage=match?.[1]??null;
  }
  const ai=audio?.defaultCaptionTrackIndex,ci=renderer.defaultCaptionTrackIndex;
  if(ai!==undefined&&ci!==undefined&&ai!==ci)return null;
  const index=ai??ci;
  if(index!==undefined){
    const chosen=indexed(index,items);if(!chosen)return null;
    if(audioLanguage&&!sameLanguage(audioLanguage,chosen.track.languageCode))return null;
    if(audio?.captionTrackIndices!==undefined&&(!Array.isArray(audio.captionTrackIndices)||!audio.captionTrackIndices.includes(index)))return null;
    return finish(chosen,ai!==undefined?'default_audio_caption_index':'default_caption_index');
  }
  if(audioLanguage){
    const linked=audio.captionTrackIndices;
    if(linked!==undefined&&(!Array.isArray(linked)||linked.some(i=>!indexed(i,items))))return null;
    const eligible=items.filter(x=>linked===undefined||linked.includes(x.index));
    const exact=eligible.filter(x=>language(x.track.languageCode)===language(audioLanguage));
    const matching=exact.length?exact:eligible.filter(x=>sameLanguage(x.track.languageCode,audioLanguage));
    if(new Set(matching.map(x=>language(x.track.languageCode))).size!==1)return null;
    return finish(preferred(matching),'default_audio_language');
  }
  if(new Set(items.map(x=>language(x.track.languageCode))).size===1)return finish(preferred(items),'single_language');
  // Alphabetical order, manual/ASR type and interface locale do not establish
  // the default audio language of a multi-language/dubbed video.
  return null;
}
export function selectionProof(chosen,trackId){return {policy:DEFAULT_POLICY,language:chosen.track.languageCode,track_id:trackId,basis:chosen.basis};}
export function hasDefaultProof(result){
  const p=result?.default_selection;
  return p?.policy===DEFAULT_POLICY&&bases.has(p.basis)&&language(p.language)===language(result.selected_language)&&p.track_id===result.track_id;
}
export function reusableDefault(result){
  if(hasDefaultProof(result))return true;
  if(result?.default_selection!==undefined)return false;
  // Legacy snapshots advertising only one language retain their old identity.
  // Missing language lists are legacy single-track records; known multi-track
  // metadata must be re-resolved instead of permanently pinning its first item.
  if(!result?.languages||Array.isArray(result.languages)&&result.languages.length===0)return typeof result?.selected_language==='string';
  if(!Array.isArray(result.languages))return false;
  const codes=new Set(result.languages.map(t=>language(t.language)));
  return codes.size===1&&codes.has(language(result.selected_language));
}
