import {SnapshotCache,digest,DATABASE_NOW_MS_SQL} from './snapshot-cache.mjs';
import {TranscriptError} from './transcript-errors.mjs';
import {metadataInput,validateMetadata} from './youtube-metadata.mjs';
import {FAILURE_CODES} from './acquisition-queue.mjs';
export class MetadataQueue{
 constructor(db,{now=()=>Date.now(),sleep=ms=>new Promise(r=>setTimeout(r,ms))}={}){this.db=db;this.now=now;this.sleep=sleep;this.cache=new SnapshotCache(db,{now});}
 async guard(fn){try{return await fn();}catch(e){if(e instanceof TranscriptError)throw e;throw new TranscriptError('storage_unavailable','Metadata storage failed.',{},true);}}
 async enqueue(owner,kind,raw){const input=metadataInput(kind,raw),id=await digest(JSON.stringify([owner,kind,input])),resource=input.video_id??input.playlist_id,now=this.now();const existing=await this.guard(()=>this.db.prepare('SELECT status FROM metadata_jobs WHERE id=?').bind(id).first());if(existing?.status==='complete')return id;const denial=await this.guard(()=>this.db.prepare("SELECT id FROM metadata_jobs WHERE owner_key=? AND kind=? AND resource_id=? AND failure_code='access_restriction' LIMIT 1").bind(owner,kind,resource).first());if(denial)throw new TranscriptError('access_restriction','Prior explicit resource denial prevents alternate metadata retrieval.');if(kind==='video_chapters'){const denied=await this.guard(()=>this.db.prepare("SELECT id FROM acquisition_jobs WHERE owner_key=? AND video_id=? AND failure_code='access_restriction' LIMIT 1").bind(owner,resource).first());if(denied)throw new TranscriptError('access_restriction','Prior explicit video denial prevents metadata retrieval.');}await this.guard(()=>this.db.prepare("INSERT INTO metadata_jobs (id,owner_key,kind,resource_id,input_json,status,created_ms,next_attempt_ms,attempts,lease_expires) VALUES (?,?,?,?,?,'queued',?,?,0,0) ON CONFLICT(id) DO UPDATE SET status='queued',attempts=0,next_attempt_ms=excluded.next_attempt_ms WHERE metadata_jobs.status='failed' AND metadata_jobs.failure_code IN ('network_failure','timeout','parsing_failure','rate_limiting') AND metadata_jobs.next_attempt_ms<=excluded.next_attempt_ms").bind(id,owner,kind,resource,JSON.stringify(input),now,now).run());return id;}
 async request(owner,kind,input,{budgetMs=12000}={}){const id=await this.enqueue(owner,kind,input),deadline=this.now()+Math.min(15000,Math.max(0,budgetMs));while(true){const row=await this.guard(()=>this.db.prepare('SELECT * FROM metadata_jobs WHERE id=? AND owner_key=?').bind(id,owner).first());if(!row)throw new TranscriptError('storage_unavailable','Metadata job is unavailable.');if(row.status==='complete')return JSON.parse(row.result_json);if(row.status==='failed')throw new TranscriptError(FAILURE_CODES.has(row.failure_code)?row.failure_code:'parsing_failure','Signed metadata acquisition failed; no alternate retrieval is attempted.',{},false);if(this.now()>=deadline||row.next_attempt_ms>deadline)throw new TranscriptError('acquisition_pending','Signed metadata acquisition is pending. Upgrade/activate the metadata-capable server worker and retry.',{retry_after_seconds:10},true);await this.sleep(Math.min(1000,deadline-this.now()));}}
 async claim(worker,capabilities,{authValidUntil=Number.MAX_SAFE_INTEGER}={}){const supported=capabilities.filter(k=>['playlist_page','video_chapters'].includes(k));if(!supported.length)return null;const now=this.now();await this.guard(()=>this.db.prepare(`UPDATE metadata_jobs SET status=CASE WHEN attempts<3 THEN 'queued' ELSE 'failed' END,failure_code='timeout',next_attempt_ms=CASE WHEN attempts<3 THEN ? ELSE ? END,lease_expires=0 WHERE status='leased' AND lease_expires<=${DATABASE_NOW_MS_SQL} AND ?>${DATABASE_NOW_MS_SQL}`).bind(now,now+900000,authValidUntil).run());const row=await this.guard(()=>this.db.prepare(`SELECT * FROM metadata_jobs WHERE status='queued' AND kind IN (${supported.map(()=>'?').join(',')}) AND next_attempt_ms<=? ORDER BY created_ms,id LIMIT 1`).bind(...supported,now).first());if(!row)return null;let claim,lease;try{claim=await this.cache.claim(row.owner_key,`metadata:${row.id}`,{authValidUntil});lease=await this.cache.lease({authValidUntil});const result=await this.guard(()=>this.db.prepare(`UPDATE metadata_jobs SET status='leased',worker_id=?,token=?,claim_key=?,global_slot=?,global_token=?,lease_expires=?,attempts=attempts+1 WHERE id=? AND status='queued' AND ?>${DATABASE_NOW_MS_SQL}`).bind(worker,claim.token,claim.key,lease.slot,lease.token,now+55000,row.id,authValidUntil).run());if(result.meta?.changes!==1){await claim();await lease();return null;}return {job_id:row.id,job_type:row.kind,input:JSON.parse(row.input_json),token:claim.token,owner_namespace:await digest(row.owner_key),lease_expires:now+55000};}catch(e){if(claim)await claim().catch(()=>{});if(lease)await lease().catch(()=>{});if(['service_busy','extraction_in_progress'].includes(e.code))return null;throw e;}}
 async submit(worker,input,{authValidUntil=Number.MAX_SAFE_INTEGER}={}){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['job_id','job_type','token','metadata','failure_code','retry_not_before_ms'].includes(k))||!['playlist_page','video_chapters'].includes(input.job_type)||!/^[a-f0-9]{64}$/.test(input.job_id??'')||!/^[a-f0-9-]{36}$/.test(input.token??'')||[input.metadata,input.failure_code].filter(Boolean).length!==1||input.retry_not_before_ms!==undefined&&(!input.failure_code||!Number.isSafeInteger(input.retry_not_before_ms)||input.retry_not_before_ms<0))throw new TranscriptError('invalid_input','Invalid typed metadata submission.');const row=await this.guard(()=>this.db.prepare('SELECT * FROM metadata_jobs WHERE id=?').bind(input.job_id).first());if(!row||row.worker_id!==worker)throw new TranscriptError('forbidden','Metadata claim belongs to another worker.');if(row.token!==input.token||row.kind!==input.job_type)throw new TranscriptError('claim_expired','Metadata lease was replaced.');if(row.status==='complete')return {status:'complete',metadata_id:row.id,replayed:true};if(['queued','failed'].includes(row.status)&&input.failure_code===row.failure_code&&row.lease_expires===0)return {status:row.status,metadata_id:row.id,replayed:true};if(row.status!=='leased'||row.lease_expires<=this.now())throw new TranscriptError('claim_expired','Metadata lease expired.');let metadata=null,status='complete',code=null,next=0;
 if(input.metadata){metadata={...validateMetadata(row.kind,input.metadata,JSON.parse(row.input_json)),metadata_id:row.id,acquisition_context:'private_signed_worker',acquisition_worker_id:row.worker_id,observed_at:new Date(this.now()).toISOString()};if(new TextEncoder().encode(JSON.stringify(metadata)).length>256*1024)throw new TranscriptError('response_too_large','Metadata result exceeds storage bound.');}else{if(!FAILURE_CODES.has(input.failure_code))throw new TranscriptError('invalid_input','Unsupported metadata failure.');code=input.failure_code;status=['network_failure','timeout','parsing_failure','rate_limiting'].includes(code)&&row.attempts<3?'queued':'failed';next=Math.max(this.now()+(status==='queued'?30000:900000),input.retry_not_before_ms??0);}
 const done="id=? AND worker_id=? AND token=? AND status=? AND lease_expires=0";
 let changes,batchError;try{changes=await this.db.batch([
 this.db.prepare(`UPDATE metadata_jobs SET status=?,result_json=?,failure_code=?,next_attempt_ms=?,lease_expires=0 WHERE id=? AND worker_id=? AND token=? AND status='leased' AND lease_expires>${DATABASE_NOW_MS_SQL} AND ?>${DATABASE_NOW_MS_SQL} AND EXISTS (SELECT 1 FROM transcript_claims WHERE request_key=? AND token=? AND expires_at>${DATABASE_NOW_MS_SQL})`).bind(status,metadata?JSON.stringify(metadata):null,code,next,row.id,worker,row.token,authValidUntil,row.claim_key,row.token),
 this.db.prepare(`UPDATE metadata_jobs SET id=CASE WHEN ?>${DATABASE_NOW_MS_SQL} AND EXISTS (SELECT 1 FROM transcript_claims WHERE request_key=? AND token=? AND expires_at>${DATABASE_NOW_MS_SQL}) THEN id ELSE NULL END WHERE ${done} AND EXISTS (SELECT 1 FROM transcript_claims WHERE request_key=? AND token=?)`).bind(authValidUntil,row.claim_key,row.token,row.id,worker,row.token,status,row.claim_key,row.token),
 this.db.prepare(`DELETE FROM transcript_claims WHERE request_key=? AND token=? AND EXISTS (SELECT 1 FROM metadata_jobs WHERE ${done})`).bind(row.claim_key,row.token,row.id,worker,row.token,status),
 this.db.prepare(`DELETE FROM extractor_leases WHERE slot=? AND token=? AND EXISTS (SELECT 1 FROM metadata_jobs WHERE ${done})`).bind(row.global_slot,row.global_token,row.id,worker,row.token,status)]);}catch(e){batchError=e;}const receipt=await this.guard(()=>this.db.prepare('SELECT status,worker_id,token,lease_expires FROM metadata_jobs WHERE id=?').bind(row.id).first());if(receipt?.status===status&&receipt.worker_id===worker&&receipt.token===row.token&&receipt.lease_expires===0){if(changes?.[0]?.meta?.changes===1&&changes.slice(1).some(c=>c.meta?.changes!==1))throw new TranscriptError('storage_unavailable','Metadata transaction did not commit its fenced mutations.',{},true);return {status,metadata_id:row.id,replayed:changes?.[0]?.meta?.changes!==1};}if(batchError)throw new TranscriptError('storage_unavailable','Metadata transaction failed without publishing a result.',{},true);throw new TranscriptError('claim_expired','Metadata transaction lost its live claim.');}
}
