import {TranscriptError} from './transcript-errors.mjs';
import {playlistId,playlistUrl} from './youtube-metadata.mjs';
import {MetadataQueue} from './metadata-queue.mjs';
import {digest,DATABASE_NOW_MS_SQL} from './snapshot-cache.mjs';
import {transcriptBatch} from './transcript-batch.mjs';
import {planWorkflowResponse,readWorkflowResponse,assertWorkflowResponse} from './workflow-response.mjs';
import {validateLanguage} from './youtube-extractor.mjs';
import {escapeMarkdown} from './transcript-markdown.mjs';
const encode=value=>btoa(JSON.stringify(value)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
function decode(value){try{if(typeof value!=='string'||value.length>256||!/^[A-Za-z0-9_-]+$/.test(value))throw new Error();const c=JSON.parse(atob(value.replace(/-/g,'+').replace(/_/g,'/')));if(c.v!==1||!/^[a-f0-9-]{36}$/.test(c.id)||!Number.isSafeInteger(c.revision)||c.revision<1)throw new Error();return c;}catch{throw new TranscriptError('invalid_cursor','Malformed playlist cursor.');}}
export function playlistArguments(raw){if(!raw||Array.isArray(raw)||Object.keys(raw).some(k=>!['playlist','limit','lang','delivery','playlist_cursor'].includes(k)))throw new TranscriptError('invalid_input','Use playlist, optional limit, lang, delivery and playlist_cursor.');const id=playlistId(raw.playlist),limit=raw.limit??10;validateLanguage(raw.lang);if(!Number.isInteger(limit)||limit<1||limit>100||raw.delivery!==undefined&&!['full','paged'].includes(raw.delivery))throw new TranscriptError('invalid_input','Playlist limit is 1–100 and delivery is full or paged.');return {id,limit,lang:raw.lang,delivery:raw.delivery??'full',cursor:raw.playlist_cursor};}
export async function playlistTool(name,service,db,input,owner,{now=()=>Date.now(),metadata=new MetadataQueue(db,{now})}={}){
 const args=playlistArguments(input),key=await digest(JSON.stringify([name,owner,args.id,args.limit,args.lang??null,args.delivery])),expires=now()-86400000,deadline=now()+45000;let row;
 if(args.cursor){const c=decode(args.cursor);row=await db.prepare('SELECT * FROM playlist_sessions WHERE id=? AND owner_key=? AND created_ms>?').bind(c.id,owner,expires).first();if(!row||row.request_key!==key)throw new TranscriptError('invalid_cursor','Playlist cursor owner/input mismatch or expired workflow.');const saved=await db.prepare('SELECT response_json FROM playlist_pages WHERE session_id=? AND revision=?').bind(row.id,c.revision).first();if(saved)return {...await readWorkflowResponse(db,"playlist",row,args.cursor?decode(args.cursor).revision:0,saved.response_json),replayed:true};if(row.revision!==c.revision)throw new TranscriptError('invalid_cursor','Playlist cursor revision mismatch.');}
 else{row=await db.prepare('SELECT * FROM playlist_sessions WHERE owner_key=? AND request_key=? AND created_ms>? ORDER BY created_ms DESC,id LIMIT 1').bind(owner,key,now()-300000).first();if(row){const saved=await db.prepare('SELECT response_json FROM playlist_pages WHERE session_id=? AND revision=0').bind(row.id).first();if(saved)return {...await readWorkflowResponse(db,"playlist",row,args.cursor?decode(args.cursor).revision:0,saved.response_json),replayed:true};}}
 if(!row){const release=await service.cache.claim(owner,`playlist:${key}`);try{row=await db.prepare('SELECT * FROM playlist_sessions WHERE owner_key=? AND request_key=? AND created_ms>? ORDER BY created_ms DESC,id LIMIT 1').bind(owner,key,now()-300000).first();if(!row){const observationEpoch=Math.floor(now()/300000);const feed=await metadata.request(owner,'playlist_page',{playlist_id:args.id,observation_epoch:observationEpoch},{budgetMs:Math.max(0,deadline-now())});const id=crypto.randomUUID(),state={observation_epoch:observationEpoch,title:feed.title,pending:feed.entries,continuation:feed.continuation,context:feed.context??null,observed:0,pages:1,continuation_hashes:[],metadata_ids:[feed.metadata_id],metadata_worker_id:feed.acquisition_worker_id,position_results:[],delivered:{},retry_positions:[],retry_round:0};await db.prepare('INSERT INTO playlist_sessions (id,owner_key,request_key,state_json,revision,created_ms,lease_expires) VALUES (?,?,?,?,0,?,0)').bind(id,owner,key,JSON.stringify(state),now()).run();row=await db.prepare('SELECT * FROM playlist_sessions WHERE id=?').bind(id).first();}}finally{await release();}}
 if(!args.cursor&&row.revision>0){const saved=await db.prepare('SELECT response_json FROM playlist_pages WHERE session_id=? AND revision=0').bind(row.id).first();if(saved)return {...await readWorkflowResponse(db,"playlist",row,args.cursor?decode(args.cursor).revision:0,saved.response_json),replayed:true};throw new TranscriptError('storage_unavailable','Initial playlist receipt is unavailable.');}
 const token=crypto.randomUUID();const locked=await db.prepare('UPDATE playlist_sessions SET lease_token=?,lease_expires=? WHERE id=? AND revision=? AND lease_expires<=?').bind(token,now()+120000,row.id,row.revision,now()).run();if(locked.meta?.changes!==1)throw new TranscriptError('extraction_in_progress','Playlist workflow is already running.',{retry_after_seconds:2},true);
 try{const state=JSON.parse(row.state_json);while(!state.pending.length&&state.continuation&&state.pages<20&&state.observed<args.limit&&!state.retry_positions?.length){const hash=await digest(state.continuation);if(state.continuation_hashes.includes(hash))throw new TranscriptError('parsing_failure','Playlist continuation repeated.');state.continuation_hashes.push(hash);const feed=await metadata.request(owner,'playlist_page',{playlist_id:args.id,continuation:state.continuation,context:state.context,observation_epoch:state.observation_epoch},{budgetMs:Math.max(0,deadline-now())});state.pending=feed.entries;state.continuation=feed.continuation;state.context=feed.context??state.context;state.metadata_ids.push(feed.metadata_id);state.pages++;}
 const retrying=!!state.retry_positions?.length,picked=retrying?state.retry_positions.slice(0,10):state.pending.slice(0,Math.min(10,args.limit-state.observed));state.delivered??={};const delivered=id=>Object.hasOwn(state.delivered,id)?state.delivered[id]:null;
 const ids=[...new Set(picked.filter(p=>p.availability==='reported_public'&&p.video_id&&!delivered(p.video_id)).map(p=>p.video_id))];
 let batch={markdown:`# ${escapeMarkdown(state.title||'Playlist')}\n\nPlaylist position metadata only. No captions requested.`,results:[],has_more:false,next_cursors:{},success_count:0,status:'success'};
 if(name==='get_playlist_transcripts'&&ids.length)batch=await transcriptBatch(service,{videos:ids,delivery:args.delivery,...(args.lang?{lang:args.lang}:{})},owner,{now,budgetMs:Math.max(0,deadline-now())});
 const positions=picked.map((p,i)=>{const result=batch.results.find(r=>r.video_id===p.video_id)??delivered(p.video_id);return {...p,position:p.reported_position,position_provenance:p.reported_position===null?'upstream_order_only_no_numeric_position':'upstream_renderer_index',observed_ordinal:retrying?p.observed_ordinal:state.observed+i+1,caption_prior_response_revision:delivered(p.video_id)?.response_revision??null,caption_snapshot_id:result?.snapshot_id??null,caption_segment_hash:result?.segment_hash??null,caption_reference:p.video_id&&p.availability==='reported_public'?p.video_id:null,...(name==='get_playlist_transcripts'?{caption_status:p.availability==='unavailable'?'unavailable':result?.ok?'success':result?.error?.code??'unavailable'}:{})};});
 const advanced=retrying?0:picked.length,total=state.observed+advanced;let pendingRetry=[];
 const remaining=total<args.limit&&(state.pending.length>advanced||!!state.continuation&&state.pages<20);
 const more=()=>remaining||pendingRetry.length>0,wrapper=value=>({...value,playlist:{id:args.id,url:playlistUrl(args.id),title:state.title,order:'public_upstream_observed_order',manifest_id:row.id,metadata_provenance:'private_signed_worker_upstream_playlist_renderers',metadata_worker_id:state.metadata_worker_id,metadata_ids:state.metadata_ids,URL_index_ignored:true,hidden_positions:'unknown',reported_total:null},positions,requested_limit:args.limit,observed_positions_this_call:picked.length,observed_positions_total:total,has_more_playlist:more(),playlist_cursor:more()?encode({v:1,id:row.id,revision:row.revision+1}):null,selection_complete:!remaining&&!(state.pages>=20&&state.continuation&&total<args.limit),caption_pending_positions:pendingRetry.map(p=>p.observed_ordinal),caption_pending_retry_exhausted:positions.some(p=>p.caption_status==='acquisition_pending')&&!pendingRetry.length,partial_reason:state.pages>=20&&state.continuation?'playlist_scan_bound':total<args.limit&&!state.continuation&&state.pending.length<=picked.length?'observed_playlist_end':null,replayed:false,caption_text_deduplicated:true,caption_continuation_tool:'get_transcripts',caption_continuation_instructions:'Use returned next_cursors with only their successful video IDs; preserve language. Playlist cursor continues positions separately, first retrying pending positions for at most three response rounds without filling from later positions. Exhausted pending IDs may be retried explicitly with get_transcripts.'});
 if(name==='get_playlist_transcripts'){for(const p of positions){const r=batch.results.find(r=>r.video_id===p.video_id)??delivered(p.video_id);if(p.availability==='reported_public')p.caption_status=r?.ok?'success':r?.error?.code??'unavailable';}pendingRetry=state.retry_round<2?positions.filter(p=>['acquisition_pending','extraction_in_progress','service_busy','timeout','network_failure','rate_limiting'].includes(p.caption_status)):[];}
 const response=wrapper(batch);if(response.partial_reason==='playlist_scan_bound')response.status='partial';if(name==='get_playlist_transcripts'&&positions.some(p=>p.caption_status!=='success'))response.status=positions.some(p=>p.caption_status==='success')?'partial':'failed';
 // Freeze each receipt; a continuation may retry the same pending positions.
 // Successful duplicate text is referenced across the entire workflow.
 for(const result of batch.results)if(result.ok)state.delivered[result.video_id]={ok:true,snapshot_id:result.snapshot_id,segment_hash:result.segment_hash,response_revision:row.revision};
 state.retry_positions=pendingRetry;state.retry_round=pendingRetry.length?state.retry_round+1:0;
 if(!retrying)state.pending=state.pending.slice(picked.length);state.observed=total;state.position_results.push(...positions.map(p=>({observed_ordinal:p.observed_ordinal,video_id:p.video_id,status:p.caption_status??p.availability})));
 const stateJson=JSON.stringify(state),commitNow=now(),prepared=await planWorkflowResponse(db,'playlist',row,token,commitNow,response);if(new TextEncoder().encode(stateJson).length>192*1024)throw new TranscriptError('response_too_large','Playlist state exceeds its bounded manifest.');
 const live=`id=? AND revision=? AND lease_token=? AND lease_expires>${DATABASE_NOW_MS_SQL} AND owner_key=?`;const mutations=await db.batch([...prepared.statements,db.prepare(`INSERT INTO playlist_pages (session_id,revision,response_json) SELECT ?,?,? WHERE EXISTS (SELECT 1 FROM playlist_sessions WHERE ${live})`).bind(row.id,row.revision,prepared.json,row.id,row.revision,token,row.owner_key),db.prepare(`UPDATE playlist_sessions SET state_json=?,revision=revision+1,lease_token=NULL,lease_expires=0 WHERE ${live}`).bind(stateJson,row.id,row.revision,token,row.owner_key),assertWorkflowResponse(db,'playlist',row,prepared,stateJson)]);if(mutations?.length!==prepared.statements.length+3||mutations.some(m=>m.meta?.changes!==1))throw new TranscriptError('extraction_in_progress','Playlist manifest commit lost its lease.',{retry_after_seconds:2},true);return response;
 }catch(e){if(e instanceof TranscriptError)throw e;throw new TranscriptError('storage_unavailable','Playlist workflow storage failed.',{},true);}finally{await db.prepare('UPDATE playlist_sessions SET lease_token=NULL,lease_expires=0 WHERE id=? AND lease_token=?').bind(row.id,token).run();}
}
