import { sqliteTable, text, integer, index, primaryKey } from 'drizzle-orm/sqlite-core';
export const snapshots=sqliteTable('transcript_snapshots',{
  id:text('id').primaryKey(),ownerKey:text('owner_key').notNull(),videoId:text('video_id').notNull(),requestLang:text('request_lang').notNull(),
  resolvedLang:text('resolved_lang').notNull(),trackId:text('track_id').notNull(),extractorVersion:text('extractor_version').notNull(),cacheKey:text('cache_key').notNull(),
  retrievedMs:integer('retrieved_ms').notNull(),expiresAt:integer('expires_at').notNull(),bytes:integer('bytes').notNull(),pageCount:integer('page_count').notNull(),metadataJson:text('metadata_json').notNull()
}, t=>[index('idx_snapshot_lookup').on(t.ownerKey,t.videoId,t.requestLang,t.extractorVersion,t.expiresAt),index('idx_snapshot_expiry').on(t.expiresAt),index('idx_snapshot_cache_key').on(t.cacheKey)]);
export const chunks=sqliteTable('transcript_chunks',{
  snapshotId:text('snapshot_id').notNull().references(()=>snapshots.id,{onDelete:'cascade'}),page:integer('page').notNull(),firstIndex:integer('first_index').notNull(),segmentsJson:text('segments_json').notNull()
},t=>[primaryKey({columns:[t.snapshotId,t.page]})]);
export const extractorLeases=sqliteTable('extractor_leases',{slot:integer('slot').primaryKey(),token:text('token').notNull(),expiresAt:integer('expires_at').notNull()});
export const transcriptClaims=sqliteTable('transcript_claims',{requestKey:text('request_key').primaryKey(),token:text('token').notNull(),expiresAt:integer('expires_at').notNull()});
export const creatorJobs=sqliteTable('creator_jobs',{id:text('id').primaryKey(),requestKey:text('request_key').notNull(),ownerKey:text('owner_key').notNull(),creatorUrl:text('creator_url').notNull(),langKey:text('lang_key').notNull(),requestedLimit:integer('requested_limit').notNull(),stateJson:text('state_json').notNull(),createdMs:integer('created_ms').notNull(),expiresAt:integer('expires_at').notNull(),revision:integer('revision').notNull(),leaseToken:text('lease_token'),leaseExpires:integer('lease_expires').notNull()},t=>[index('idx_creator_recent').on(t.requestKey,t.createdMs)]);
export const creatorJobPages=sqliteTable('creator_job_pages',{jobId:text('job_id').notNull().references(()=>creatorJobs.id,{onDelete:'cascade'}),revision:integer('revision').notNull(),responseJson:text('response_json').notNull()},t=>[primaryKey({columns:[t.jobId,t.revision]})]);
export const creatorResponseChunks=sqliteTable('creator_response_chunks',{jobId:text('job_id').notNull().references(()=>creatorJobs.id,{onDelete:'cascade'}),revision:integer('revision').notNull(),part:integer('part').notNull(),body:text('body').notNull()},t=>[primaryKey({columns:[t.jobId,t.revision,t.part]})]);
export const acquisitionJobs=sqliteTable('acquisition_jobs',{
  id:text('id').primaryKey(),ownerKey:text('owner_key').notNull(),videoId:text('video_id').notNull(),langKey:text('lang_key').notNull(),status:text('status').notNull(),createdMs:integer('created_ms').notNull(),nextAttemptMs:integer('next_attempt_ms').notNull(),attempts:integer('attempts').notNull(),leaseExpires:integer('lease_expires').notNull(),workerId:text('worker_id'),token:text('token'),claimKey:text('claim_key'),globalSlot:integer('global_slot'),globalToken:text('global_token'),failureCode:text('failure_code'),snapshotId:text('snapshot_id')
},t=>[index('idx_acquisition_pending').on(t.status,t.nextAttemptMs,t.createdMs)]);
export const acquisitionNonces=sqliteTable('acquisition_nonces',{workerId:text('worker_id').notNull(),nonce:text('nonce').notNull(),expiresAt:integer('expires_at').notNull()},t=>[primaryKey({columns:[t.workerId,t.nonce]}),index('idx_acquisition_nonce_expiry').on(t.expiresAt)]);

export const transcriptDefaults=sqliteTable('transcript_defaults',{ownerKey:text('owner_key').notNull(),videoId:text('video_id').notNull(),policy:text('policy').notNull(),snapshotId:text('snapshot_id').notNull()},t=>[primaryKey({columns:[t.ownerKey,t.videoId,t.policy]})]);
export const metadataJobs=sqliteTable('metadata_jobs',{id:text('id').primaryKey(),ownerKey:text('owner_key').notNull(),kind:text('kind').notNull(),resourceId:text('resource_id').notNull(),inputJson:text('input_json').notNull(),status:text('status').notNull(),createdMs:integer('created_ms').notNull(),nextAttemptMs:integer('next_attempt_ms').notNull(),attempts:integer('attempts').notNull(),leaseExpires:integer('lease_expires').notNull(),workerId:text('worker_id'),token:text('token'),claimKey:text('claim_key'),globalSlot:integer('global_slot'),globalToken:text('global_token'),failureCode:text('failure_code'),resultJson:text('result_json')},t=>[index('idx_metadata_pending').on(t.status,t.nextAttemptMs,t.createdMs)]);
export const playlistSessions=sqliteTable('playlist_sessions',{id:text('id').primaryKey(),ownerKey:text('owner_key').notNull(),requestKey:text('request_key').notNull(),stateJson:text('state_json').notNull(),revision:integer('revision').notNull(),createdMs:integer('created_ms').notNull(),leaseToken:text('lease_token'),leaseExpires:integer('lease_expires').notNull()},t=>[index('idx_playlist_request').on(t.ownerKey,t.requestKey,t.createdMs)]);
export const playlistPages=sqliteTable('playlist_pages',{sessionId:text('session_id').notNull().references(()=>playlistSessions.id,{onDelete:'cascade'}),revision:integer('revision').notNull(),responseJson:text('response_json').notNull()},t=>[primaryKey({columns:[t.sessionId,t.revision]})]);
export const playlistResponseChunks=sqliteTable('playlist_response_chunks',{sessionId:text('session_id').notNull().references(()=>playlistSessions.id,{onDelete:'cascade'}),revision:integer('revision').notNull(),part:integer('part').notNull(),body:text('body').notNull()},t=>[primaryKey({columns:[t.sessionId,t.revision,t.part]})]);
export const chapterManifests=sqliteTable('chapter_manifests',{id:text('id').primaryKey(),ownerKey:text('owner_key').notNull(),videoId:text('video_id').notNull(),createdMs:integer('created_ms').notNull(),documentJson:text('document_json').notNull()});
